info:
  component: Config Server
spring:
  config:
    name: configserver
  profiles:
    active: custom
  application:
    name: configserver
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      watch:
        enabled: true
        initialDelay: 500
        delay: 1000
server:
  port: 8888
management:
  context_path: /admin
